defaults: &defaults
  version: 809
  # use local file as default
  #wsdl_file: 'http://developer.ebay.com/webservices/809/eBaySvc.wsdl'
  routing: default
  siteid: 0
  preload: false
  warning_level: Low
  error_language: en_US
  api_keys: []
  savon_log_level: debug

development: &development
  <<: *defaults
  url: 'https://api.sandbox.ebay.com/wsapi'
  warning_level: High
  savon_log_level: info

test:
  <<: *development

production:
  <<: *defaults
  url: 'https://api.ebay.com/wsapi'
  preload: true
